add missing functions

diff --git a/modules/openvpn-vagrant-client/install-requirements b/modules/openvpn-vagrant-client/install-requirements
--- a/modules/openvpn-vagrant-client/install-requirements
+++ b/modules/openvpn-vagrant-client/install-requirements
@@ -1,5 +1,42 @@
 #!/bin/bash
 
+function print_usage {
+  echo
+  echo "Usage: ./install-requirements [OPTIONS]"
+  echo
+  echo "This script to initialise pacakges required for the VPN."
+  echo
+  echo "Options:"
+  echo
+  echo -e "  --host-type\t\tUse either 'metal' or 'vagrant' to decide the environment we are provisioning for."
+  echo
+  echo "Example:"
+  echo
+  echo "  ./install-requirements --host-type='metal'"
+}
+
+function log {
+  local -r level="$1"
+  local -r message="$2"
+  local -r timestamp=$(date +"%Y-%m-%d %H:%M:%S")
+  >&2 echo -e "${timestamp} [${level}] [$SCRIPT_NAME] ${message}"
+}
+
+function log_info {
+  local -r message="$1"
+  log "INFO" "$message"
+}
+
+function log_warn {
+  local -r message="$1"
+  log "WARN" "$message"
+}
+
+function log_error {
+  local -r message="$1"
+  log "ERROR" "$message"
+}
+
 function has_yum {
   [[ -n "$(command -v yum)" ]]
 }
