test-remote-vault-request

diff --git a/modules/openvpn-vagrant-client/scripts/get-vault-file b/modules/openvpn-vagrant-client/scripts/get-vault-file
--- a/modules/openvpn-vagrant-client/scripts/get-vault-file
+++ b/modules/openvpn-vagrant-client/scripts/get-vault-file
@@ -90,14 +90,32 @@ function assert_not_empty {
 #  >&2 echo -e "$timestamp $message"
 # }
 
+function get_file_remote() {
+  local -r host1=$1
+  local -r host2=$2
+  local -r VAULT_TOKEN=$3
+  local -r source_file_path=$4
+  local -r source_vault_path=$5
+  log "Requesting files from vault to client in private subnet"
+  ssh -o ProxyCommand="ssh $host1 -W %h:%p" $host2 "VAULT_TOKEN=$VAULT_TOKEN bash -s" < $SCRIPTDIR/request_vault_file.sh "$source_file_path" "$source_vault_path"
+}
+
 function retrieve_file {
-  local -r source_path="/home/$bastion_user/tmp$1"
-  local -r target_path="$2"
+  local -r host1=$1
+  local -r host2=$2
+  local -r target_path="$4"
+  local -r bastion_user="$5"
+  local -r base_path="/home/$bastion_user/tmp"
+  local -r source_path="${base_path}$3"
 
   echo "Copy: $source_path to localhost: $target_path"
 
   scp -i ~/.ssh/id_rsa-cert.pub -i ~/.ssh/id_rsa -o ProxyCommand="ssh -i ~/.ssh/id_rsa-cert.pub -i ~/.ssh/id_rsa -W %h:%p $host1" $host2:$source_path "$target_path"
   chmod 0600 "$target_path"
+
+  # Clean up
+  log "...Cleaning up"
+  ssh -o ProxyCommand="ssh $host1 -W %h:%p" $host2 "sudo rm -frv $base_path/*"
 
   [[ -s "$target_path" ]] && exit_status=0 || exit_status=1
   if [[ $exit_status -eq 1 ]]; then
@@ -106,6 +124,47 @@ function retrieve_file {
   else 
     echo "Success"
   fi
+}
+
+function get_file_stdout() { # uses stdout to retrieve vault data, avoiding the need to store a file on a remote bastion host.
+  local -r host1=$1
+  local -r host2=$2
+  local -r token="$3"
+  local -r source_vault_path="$4"
+  local -r target_path="$5"
+
+  response=$(ssh -o ProxyCommand="ssh $host1 -W %h:%p" $host2 "bash -s" < $SCRIPTDIR/request_stdout.sh "$source_vault_path" "$token")
+
+  errors=$(echo "$response" | jq -r '.errors | length')
+  if [[ ! $errors -eq 0 ]]; then
+    echo "Vault request failed: $response"
+    exit 1
+  fi
+  
+  echo "mkdir: $(dirname $target_path)"
+  mkdir -p "$(dirname $target_path)" # ensure the directory exists
+  echo "Check file path is writable: $target_path"
+  if test -f "$target_path"; then
+    echo "File exists: ensuring it is writeable"
+    chmod u+w "$target_path"
+    touch "$target_path"
+  else
+    echo "Ensuring path is writeable"
+    touch "$target_path"
+    chmod u+w "$target_path"
+  fi
+  if [[ -f "$target_path" ]]; then
+    chmod u+w "$target_path"
+  else
+    echo "Error: path does not exist, var may not be a file: $target_path "
+  fi
+  echo "Write file content: single operation"
+  echo "$response" | jq -r '.data.data.value' | base64 --decode > $target_path
+  if [[ ! -f "$target_path" ]] || [[ -z "$(cat $target_path)" ]]; then
+    echo "Error: no file or empty result at $target_path"
+    exit 1
+  fi
+  echo "Request Complete."
 }
 
 function getfile {
@@ -130,10 +189,10 @@ function getfile {
         host2="$2"
         shift
         ;;
-      --source-file-path)
-        source_file_path="$2"
-        shift
-        ;;
+      # --source-file-path)
+      #   source_file_path="$2"
+      #   shift
+      #   ;;
       --source-vault-path)
         source_vault_path="$2"
         shift
@@ -163,7 +222,7 @@ function getfile {
   assert_not_empty "--resourcetier" "$resourcetier"
   assert_not_empty "--host1" "$host1"
   assert_not_empty "--host2" "$host2"
-  assert_not_empty "--source-file-path" "$source_file_path"
+  # assert_not_empty "--source-file-path" "$source_file_path"
   assert_not_empty "--source-vault-path" "$source_vault_path"
   assert_not_empty "--target-path" "$target_path"
 
@@ -174,16 +233,13 @@ function getfile {
 
   bastion_user="$(echo $host2 | awk -F '@' '{print $1}')"
 
+  # Retrieve generated secrets from Vault.  Would be better if we can use vault as an intermediary to generate certs.
   log_info "Aquiring file from Vault"
+  # These are temproraily disabled, but should be preserved to retain a procedure to store a file from vault remotely.
+  # get_file_remote "$host1" "$host2" "$VAULT_TOKEN" "$source_file_path" "$source_vault_path" # This method uses a reqest to store the file remotely.  Recommended only if this is the final destination of the secret.
+  # retrieve_file "$host1" "$host2" "$source_file_path" "$target_path" "$bastion_user"
 
-  log "Requesting files from vault to client in private subnet"
-  ssh -o ProxyCommand="ssh $host1 -W %h:%p" $host2 "VAULT_TOKEN=$VAULT_TOKEN bash -s" < $SCRIPTDIR/request_vault_file.sh "$source_file_path" "$source_vault_path"
-  
-  # Retrieve previously generated secrets from Vault.  Would be better if we can use vault as an intermediary to generate certs.
-  retrieve_file "$source_file_path" "$target_path"
-  # Clean up
-  log "...Cleaning up"
-  ssh -o ProxyCommand="ssh $host1 -W %h:%p" $host2 "sudo rm -frv /home/$bastion_user/tmp/*"
+  get_file_stdout "$host1" "$host2" "$VAULT_TOKEN" "$source_vault_path" "$target_path"
 
   if test -f $target_path; then
     log_info "File aquired!"
@@ -194,5 +250,7 @@ function getfile {
     exit 1;
   fi
 }
+
+
 
 getfile "$@"
