sqs-vpn

diff --git a/modules/openvpn-vagrant-client/scripts/get-vpn-info b/modules/openvpn-vagrant-client/scripts/get-vpn-info
--- a/modules/openvpn-vagrant-client/scripts/get-vpn-info
+++ b/modules/openvpn-vagrant-client/scripts/get-vpn-info
@@ -47,6 +47,22 @@ function log_error {
   log "ERROR" "$message"
 }
 
+function ssm_get_parm {
+  local -r parm_name="$1"
+
+  output=$(aws ssm get-parameters --names ${parm_name}) && exit_status=0 || exit_status=$?
+
+  invalid=$(echo ${output} | jq -r .'InvalidParameters | length')
+  if [[ $exit_status -eq 0 && $invalid -eq 0 ]]; then
+      log "Result: ${output}"
+      value=$(echo ${output} | jq -r '.Parameters[0].Value')
+      echo "$value"
+      return
+  fi
+  log "...Failed retrieving: ${parm_name}"
+  log "Result: ${output}"
+}
+
 function assert_not_empty {
   local -r arg_name="$1"
   local -r arg_value="$2"
@@ -58,50 +74,7 @@ function assert_not_empty {
   fi
 }
 
-# # Log the given message. All logs are written to stderr with a timestamp.
-# function log {
-#  local -r message="$1"
-#  local -r timestamp=$(date +"%Y-%m-%d %H:%M:%S")
-#  >&2 echo -e "$timestamp $message"
-# }
-
-function get_file_remote() {
-  local -r host1=$1
-  local -r host2=$2
-  local -r VAULT_TOKEN=$3
-  local -r source_file_path=$4
-  local -r source_vault_path=$5
-  log "Requesting files from vault to client in private subnet"
-  ssh -o ProxyCommand="ssh $host1 -W %h:%p" $host2 "VAULT_TOKEN=$VAULT_TOKEN bash -s" < $SCRIPTDIR/request_vault_file.sh "$source_file_path" "$source_vault_path"
-}
-
-function retrieve_file {
-  local -r host1=$1
-  local -r host2=$2
-  local -r target_path="$4"
-  local -r bastion_user="$5"
-  local -r base_path="/home/$bastion_user/tmp"
-  local -r source_path="${base_path}$3"
-
-  echo "Copy: $source_path to localhost: $target_path"
-
-  scp -i ~/.ssh/id_rsa-cert.pub -i ~/.ssh/id_rsa -o ProxyCommand="ssh -i ~/.ssh/id_rsa-cert.pub -i ~/.ssh/id_rsa -W %h:%p $host1" $host2:$source_path "$target_path"
-  chmod 0600 "$target_path"
-
-  # Clean up
-  log "...Cleaning up"
-  ssh -o ProxyCommand="ssh $host1 -W %h:%p" $host2 "sudo rm -frv $base_path/*"
-
-  [[ -s "$target_path" ]] && exit_status=0 || exit_status=1
-  if [[ $exit_status -eq 1 ]]; then
-    echo "Error retrieving file"
-    exit 1
-  else 
-    echo "Success"
-  fi
-}
-
-function getfile {
+function getdata {
   local version=""
   local download_url=""
   local path="$DEFAULT_INSTALL_PATH"
@@ -109,6 +82,8 @@ function getfile {
 
   while [[ $# > 0 ]]; do
     local key="$1"
+    local host1=""
+    local host2=""
 
     case "$key" in
       --host1)
@@ -145,37 +120,38 @@ function getfile {
     shift
   done
 
-  assert_not_empty "--host1" "$host1"
-  assert_not_empty "--host2" "$host2"
+  # assert_not_empty "--host1" "$host1"
+  # assert_not_empty "--host2" "$host2"
   assert_not_empty "--resourcetier" "$resourcetier"
   assert_not_empty "--target-path" "$target_path"
 
-  if [[ -z "$VAULT_TOKEN" ]]; then
-    echo "Provide a vault token to utilise on the private vault client:"
-    read -s -p "VAULT_TOKEN: " VAULT_TOKEN
+  if [[ ! -z "$host1" ]] && [[ ! -z "$host2" ]]; then
+    if [[ -z "$VAULT_TOKEN" ]]; then
+      echo "Provide a vault token to utilise on the private vault client:"
+      read -s -p "VAULT_TOKEN: " VAULT_TOKEN
+    fi
+    # Retrieve generated secrets from Vault.  Would be better if we can use vault as an intermediary to generate certs.
+    log_info "Aquiring values from Vault"
+
+    onsite_private_vpn_ip=$(ssh -o ProxyCommand="ssh $host1 -W %h:%p" $host2 "bash -s" < $SCRIPTDIR/request_stdout.sh "$resourcetier/data/vpn/onsite_private_vpn_ip" "$VAULT_TOKEN" | jq -r '.data.data.value')
+    onsite_private_vpn_mac=$(ssh -o ProxyCommand="ssh $host1 -W %h:%p" $host2 "bash -s" < $SCRIPTDIR/request_stdout.sh "$resourcetier/data/vpn/onsite_private_vpn_mac" "$VAULT_TOKEN" | jq -r '.data.data.value')
+  else
+    log_info "Aquiring values from SSM Parameter Store"
+
+    onsite_private_vpn_ip=$(ssm_get_parm /firehawk/resourcetier/${resourcetier}/onsite_private_vpn_ip)
+    onsite_private_vpn_mac=$(ssm_get_parm /firehawk/resourcetier/${resourcetier}/onsite_private_vpn_mac)
   fi
 
-  bastion_user="$(echo $host2 | awk -F '@' '{print $1}')"
-
-  # Retrieve generated secrets from Vault.  Would be better if we can use vault as an intermediary to generate certs.
-  log_info "Aquiring values from Vault"
-
-  onsite_private_vpn_ip=$(ssh -o ProxyCommand="ssh $host1 -W %h:%p" $host2 "bash -s" < $SCRIPTDIR/request_stdout.sh "$resourcetier/data/vpn/onsite_private_vpn_ip" "$VAULT_TOKEN" | jq -r '.data.data.value')
-  onsite_private_vpn_mac=$(ssh -o ProxyCommand="ssh $host1 -W %h:%p" $host2 "bash -s" < $SCRIPTDIR/request_stdout.sh "$resourcetier/data/vpn/onsite_private_vpn_mac" "$VAULT_TOKEN" | jq -r '.data.data.value')
+  echo "onsite_private_vpn_ip: $onsite_private_vpn_ip"
   echo "onsite_private_vpn_mac: $onsite_private_vpn_mac"
-
-  echo "{\"$resourcetier\": {\"onsite_private_vpn_mac\" : \"$onsite_private_vpn_mac\", \"onsite_private_vpn_ip\" : \"$onsite_private_vpn_ip\" }}" | jq . > $target_path
+  echo "{\"resourcetier\": \"$resourcetier\", \"$resourcetier\": {\"onsite_private_vpn_mac\" : \"$onsite_private_vpn_mac\", \"onsite_private_vpn_ip\" : \"$onsite_private_vpn_ip\" }}" | jq . > $target_path
 
   if test -f $target_path; then
-    log_info "File aquired!"
-    # cd "$EXECDIR"
+    log_info "IP and MAC address aquired!"
   else
     log_info "Could not aquire data. Aborting.";
-    # cd "$EXECDIR"
     exit 1;
   fi
 }
 
-
-
-getfile "$@"
+getdata "$@"
diff --git a/modules/openvpn-vagrant-client/wake b/modules/openvpn-vagrant-client/wake
--- a/modules/openvpn-vagrant-client/wake
+++ b/modules/openvpn-vagrant-client/wake
@@ -11,71 +11,73 @@ if [[ -z "$1" ]]; then
     exit 1
 fi
 
+# if [[ -z "$2" ]]; then
+#   echo "Error: 2nd arg bastion host must be provided. eg:"
+#   echo "./copy_vault_file_from_bastion.sh main centos@ec2-3-25-143-13.ap-southeast-2.compute.amazonaws.com centos@i-0df3060971160cdd6.node.consul"
+#   exit 1
+# fi
 
-if [[ -z "$2" ]]; then
-  echo "Error: 2nd arg bastion host must be provided. eg:"
-  echo "./copy_vault_file_from_bastion.sh main centos@ec2-3-25-143-13.ap-southeast-2.compute.amazonaws.com centos@i-0df3060971160cdd6.node.consul"
-  exit 1
-fi
+# if [[ -z "$3" ]]; then
+#   echo "Error: 3rd arg vault client must be provided. eg: centos@i-00265f3f7614cbbee.node.consul"
+#   echo "./copy_vault_file_from_bastion.sh main centos@ec2-3-25-143-13.ap-southeast-2.compute.amazonaws.com centos@i-0df3060971160cdd6.node.consul"
+#   exit 1
+# fi
 
-if [[ -z "$3" ]]; then
-  echo "Error: 3rd arg vault client must be provided. eg: centos@i-00265f3f7614cbbee.node.consul"
-  echo "./copy_vault_file_from_bastion.sh main centos@ec2-3-25-143-13.ap-southeast-2.compute.amazonaws.com centos@i-0df3060971160cdd6.node.consul"
-  exit 1
-fi
-
-if [[ -z "$VAULT_TOKEN" ]]; then
-  echo "You can generate a token to login and retrieve the VPN config with:"
-  echo ""
-  echo "vault token create -policy=vpn_read_config -policy=deadline_client -explicit-max-ttl=5m -ttl=5m -use-limit=4"
-  echo ""
-  echo "Provide a vault token to utilise on the private vault client:"
-  read -s -p "VAULT_TOKEN: " VAULT_TOKEN
-  echo ""
-fi
+# if [[ -z "$VAULT_TOKEN" ]]; then
+#   echo "You can generate a token to login and retrieve the VPN config with:"
+#   echo ""
+#   echo "vault token create -policy=vpn_read_config -policy=deadline_client -explicit-max-ttl=5m -ttl=5m -use-limit=4"
+#   echo ""
+#   echo "Provide a vault token to utilise on the private vault client:"
+#   read -s -p "VAULT_TOKEN: " VAULT_TOKEN
+#   echo ""
+# fi
 
 export resourcetier="$1"
 echo "resourcetier: $resourcetier"
-host1="$2"
-host2="$3"
 
-openvpn_user="openvpnas"
+# host1="$2"
+# host2="$3"
 
-if [[ -z "$openvpn_user_pw" ]]; then
-    echo "After establishing SSH forwarding, retrieve the VPN password from the Vault UI https://127.0.0.1:8200/ui"
-    read -s -p "openvpn_user_pw: " openvpn_user_pw
-fi
+# openvpn_user="openvpnas"
 
-if [[ -z "$openvpn_user_pw" ]]; then
-    echo "ERROR: provided openvpn_user_pw is empty.  Try again."
-    exit 1
-fi
+# if [[ -z "$openvpn_user_pw" ]]; then
+#     echo "After establishing SSH forwarding, retrieve the VPN password from the Vault UI https://127.0.0.1:8200/ui"
+#     read -s -p "openvpn_user_pw: " openvpn_user_pw
+# fi
 
-echo "openvpn_user: $openvpn_user"
+# if [[ -z "$openvpn_user_pw" ]]; then
+#     echo "ERROR: provided openvpn_user_pw is empty.  Try again."
+#     exit 1
+# fi
+
+# echo "openvpn_user: $openvpn_user"
+
 target_path="$SCRIPTDIR/ip_addresses.json"
 echo "Request VPN IP and MAC address"
-$SCRIPTDIR/scripts/get-vpn-info --host1 $host1 --host2 $host2 --target-path $target_path --resourcetier $resourcetier --vault-token $VAULT_TOKEN
+# $SCRIPTDIR/scripts/get-vpn-info --host1 $host1 --host2 $host2 --target-path $target_path --resourcetier $resourcetier --vault-token $VAULT_TOKEN
+$SCRIPTDIR/scripts/get-vpn-info --target-path $target_path --resourcetier $resourcetier # This method uses AWS creds to read the VM IP and MAC data from SSM parameter store.
 
-echo "Request the VPN config / certs"
-source_file_path="/usr/local/openvpn_as/scripts/seperate/client.ovpn" # the original file path that was stored in vault
-source_vault_path="$resourcetier/data/vpn/client_cert_files$source_file_path" # the full namespace / path to the file in vault.
-target_path="$SCRIPTDIR/openvpn_config/$(basename $source_file_path)"
+# echo "Request the VPN config / certs"
+# source_file_path="/usr/local/openvpn_as/scripts/seperate/client.ovpn" # the original file path that was stored in vault
+# source_vault_path="$resourcetier/data/vpn/client_cert_files$source_file_path" # the full namespace / path to the file in vault.
+# target_path="$SCRIPTDIR/openvpn_config/$(basename $source_file_path)"
 
-rm -f $SCRIPTDIR/openvpn_config/client.ovpn
-rm -f $SCRIPTDIR/openvpn_config/openvpn.conf
+# rm -f $SCRIPTDIR/openvpn_config/client.ovpn
+# rm -f $SCRIPTDIR/openvpn_config/openvpn.conf
 
-$SCRIPTDIR/scripts/get-vault-file --host1 $host1 --host2 $host2 --source-vault-path $source_vault_path --target-path $target_path --vault-token $VAULT_TOKEN
+# $SCRIPTDIR/scripts/get-vault-file --host1 $host1 --host2 $host2 --source-vault-path $source_vault_path --target-path $target_path --vault-token $VAULT_TOKEN
 
-# Replicate file for vpn.  This might be able to be deprecated, or replaced with a move
-cp -f $SCRIPTDIR/openvpn_config/client.ovpn $SCRIPTDIR/openvpn_config/openvpn.conf
+# # Replicate file for vpn.  This might be able to be deprecated, or replaced with a move
+# cp -f $SCRIPTDIR/openvpn_config/client.ovpn $SCRIPTDIR/openvpn_config/openvpn.conf
 
-echo "Request the deadline client certifcate."
-source_file_path="/opt/Thinkbox/certs/Deadline10RemoteClient.pfx" # the original file path that was stored in vault
-source_vault_path="$resourcetier/data/deadline/client_cert_files$source_file_path" # the full namespace / path to the file in vault.
-target_path="$HOME/.ssh/$(basename $source_file_path)"
+# echo "Request the deadline client certifcate."
+# source_file_path="/opt/Thinkbox/certs/Deadline10RemoteClient.pfx" # the original file path that was stored in vault
+# source_vault_path="$resourcetier/data/deadline/client_cert_files$source_file_path" # the full namespace / path to the file in vault.
+# target_path="$HOME/.ssh/$(basename $source_file_path)"
 
-$SCRIPTDIR/scripts/get-vault-file --host1 $host1 --host2 $host2 --source-vault-path $source_vault_path --target-path $target_path --vault-token $VAULT_TOKEN
+# $SCRIPTDIR/scripts/get-vault-file --host1 $host1 --host2 $host2 --source-vault-path $source_vault_path --target-path $target_path --vault-token $VAULT_TOKEN
 
+# openvpn_user=$openvpn_user openvpn_user_pw=$openvpn_user_pw vagrant up
 
-
-openvpn_user=$openvpn_user openvpn_user_pw=$openvpn_user_pw vagrant up
+vagrant up
